version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres



  liquibase-migrations:
    image: liquibase/liquibase:4.26-alpine
    container_name: liquibase
    depends_on:
      - db
    command:
      - --changelog-file=master.xml
      - --search-path=/liquibase/changelog/
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://db:5432/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./scrapper/src/main/resources/migrations/:/liquibase/changelog/
