package edu.java.models.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_update.proto

@SuppressWarnings(value = {"EmptyLineSeparator", "TypeName", "RedundantModifier",
    "CyclomaticComplexity", "LocalVariableName", "MagicNumber", "MemberName",
    "EmptyBlock", "OperatorWrap", "InnerTypeLast", "WhitespaceAfter",
    "AvoidNestedBlocks", "ConstantName", "LineLength", "NoClone"})
public final class LinkUpdate {
    private LinkUpdate() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry
    ) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry
    ) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface link_updateOrBuilder extends
        // @@protoc_insertion_point(interface_extends:link_update)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int64 id = 1;</code>
         *
         * @return The id.
         */
        long getId();

        /**
         * <code>string creator = 2;</code>
         *
         * @return The creator.
         */
        java.lang.String getCreator();

        /**
         * <code>string creator = 2;</code>
         *
         * @return The bytes for creator.
         */
        com.google.protobuf.ByteString
        getCreatorBytes();

        /**
         * <code>string url = 3;</code>
         *
         * @return The url.
         */
        java.lang.String getUrl();

        /**
         * <code>string url = 3;</code>
         *
         * @return The bytes for url.
         */
        com.google.protobuf.ByteString
        getUrlBytes();

        /**
         * <code>string description = 4;</code>
         *
         * @return The description.
         */
        java.lang.String getDescription();

        /**
         * <code>string description = 4;</code>
         *
         * @return The bytes for description.
         */
        com.google.protobuf.ByteString
        getDescriptionBytes();

        /**
         * <code>repeated int64 tgChatIds = 5;</code>
         *
         * @return A list containing the tgChatIds.
         */
        java.util.List<java.lang.Long> getTgChatIdsList();

        /**
         * <code>repeated int64 tgChatIds = 5;</code>
         *
         * @return The count of tgChatIds.
         */
        int getTgChatIdsCount();

        /**
         * <code>repeated int64 tgChatIds = 5;</code>
         *
         * @param index The index of the element to return.
         * @return The tgChatIds at the given index.
         */
        long getTgChatIds(int index);
    }

    /**
     * Protobuf type {@code link_update}
     */
    public static final class link_update extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:link_update)
        link_updateOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use link_update.newBuilder() to construct.
        private link_update(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private link_update() {
            creator_ = "";
            url_ = "";
            description_ = "";
            tgChatIds_ = emptyLongList();
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
            UnusedPrivateParameter unused
        ) {
            return new link_update();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private link_update(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry
        )
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            id_ = input.readInt64();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            creator_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            url_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            description_ = s;
                            break;
                        }
                        case 40: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                tgChatIds_ = newLongList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            tgChatIds_.addLong(input.readInt64());
                            break;
                        }
                        case 42: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                                tgChatIds_ = newLongList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                tgChatIds_.addLong(input.readInt64());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    tgChatIds_.makeImmutable(); // C
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return LinkUpdate.internal_static_link_update_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return LinkUpdate.internal_static_link_update_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    LinkUpdate.link_update.class, LinkUpdate.link_update.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private long id_;

        /**
         * <code>int64 id = 1;</code>
         *
         * @return The id.
         */
        @java.lang.Override
        public long getId() {
            return id_;
        }

        public static final int CREATOR_FIELD_NUMBER = 2;
        private volatile java.lang.Object creator_;

        /**
         * <code>string creator = 2;</code>
         *
         * @return The creator.
         */
        @java.lang.Override
        public java.lang.String getCreator() {
            java.lang.Object ref = creator_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                creator_ = s;
                return s;
            }
        }

        /**
         * <code>string creator = 2;</code>
         *
         * @return The bytes for creator.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getCreatorBytes() {
            java.lang.Object ref = creator_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                creator_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int URL_FIELD_NUMBER = 3;
        private volatile java.lang.Object url_;

        /**
         * <code>string url = 3;</code>
         *
         * @return The url.
         */
        @java.lang.Override
        public java.lang.String getUrl() {
            java.lang.Object ref = url_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                url_ = s;
                return s;
            }
        }

        /**
         * <code>string url = 3;</code>
         *
         * @return The bytes for url.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUrlBytes() {
            java.lang.Object ref = url_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                url_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DESCRIPTION_FIELD_NUMBER = 4;
        private volatile java.lang.Object description_;

        /**
         * <code>string description = 4;</code>
         *
         * @return The description.
         */
        @java.lang.Override
        public java.lang.String getDescription() {
            java.lang.Object ref = description_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                description_ = s;
                return s;
            }
        }

        /**
         * <code>string description = 4;</code>
         *
         * @return The bytes for description.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getDescriptionBytes() {
            java.lang.Object ref = description_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                description_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TGCHATIDS_FIELD_NUMBER = 5;
        private com.google.protobuf.Internal.LongList tgChatIds_;

        /**
         * <code>repeated int64 tgChatIds = 5;</code>
         *
         * @return A list containing the tgChatIds.
         */
        @java.lang.Override
        public java.util.List<java.lang.Long>
        getTgChatIdsList() {
            return tgChatIds_;
        }

        /**
         * <code>repeated int64 tgChatIds = 5;</code>
         *
         * @return The count of tgChatIds.
         */
        public int getTgChatIdsCount() {
            return tgChatIds_.size();
        }

        /**
         * <code>repeated int64 tgChatIds = 5;</code>
         *
         * @param index The index of the element to return.
         * @return The tgChatIds at the given index.
         */
        public long getTgChatIds(int index) {
            return tgChatIds_.getLong(index);
        }

        private int tgChatIdsMemoizedSerializedSize = -1;

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            getSerializedSize();
            if (id_ != 0L) {
                output.writeInt64(1, id_);
            }
            if (!getCreatorBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, creator_);
            }
            if (!getUrlBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, url_);
            }
            if (!getDescriptionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
            }
            if (getTgChatIdsList().size() > 0) {
                output.writeUInt32NoTag(42);
                output.writeUInt32NoTag(tgChatIdsMemoizedSerializedSize);
            }
            for (int i = 0; i < tgChatIds_.size(); i++) {
                output.writeInt64NoTag(tgChatIds_.getLong(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, id_);
            }
            if (!getCreatorBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, creator_);
            }
            if (!getUrlBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, url_);
            }
            if (!getDescriptionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < tgChatIds_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                        .computeInt64SizeNoTag(tgChatIds_.getLong(i));
                }
                size += dataSize;
                if (!getTgChatIdsList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                        .computeInt32SizeNoTag(dataSize);
                }
                tgChatIdsMemoizedSerializedSize = dataSize;
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof LinkUpdate.link_update)) {
                return super.equals(obj);
            }
            LinkUpdate.link_update other = (LinkUpdate.link_update) obj;

            if (getId()
                != other.getId()) {
                return false;
            }
            if (!getCreator()
                .equals(other.getCreator())) {
                return false;
            }
            if (!getUrl()
                .equals(other.getUrl())) {
                return false;
            }
            if (!getDescription()
                .equals(other.getDescription())) {
                return false;
            }
            if (!getTgChatIdsList()
                .equals(other.getTgChatIdsList())) {
                return false;
            }
            if (!unknownFields.equals(other.unknownFields)) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getId());
            hash = (37 * hash) + CREATOR_FIELD_NUMBER;
            hash = (53 * hash) + getCreator().hashCode();
            hash = (37 * hash) + URL_FIELD_NUMBER;
            hash = (53 * hash) + getUrl().hashCode();
            hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
            hash = (53 * hash) + getDescription().hashCode();
            if (getTgChatIdsCount() > 0) {
                hash = (37 * hash) + TGCHATIDS_FIELD_NUMBER;
                hash = (53 * hash) + getTgChatIdsList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static LinkUpdate.link_update parseFrom(
            java.nio.ByteBuffer data
        )
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static LinkUpdate.link_update parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry
        )
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static LinkUpdate.link_update parseFrom(
            com.google.protobuf.ByteString data
        )
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static LinkUpdate.link_update parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry
        )
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static LinkUpdate.link_update parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static LinkUpdate.link_update parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry
        )
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static LinkUpdate.link_update parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static LinkUpdate.link_update parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry
        )
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static LinkUpdate.link_update parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
        }

        public static LinkUpdate.link_update parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry
        )
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static LinkUpdate.link_update parseFrom(
            com.google.protobuf.CodedInputStream input
        )
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static LinkUpdate.link_update parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry
        )
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(LinkUpdate.link_update prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent
        ) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code link_update}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:link_update)
            LinkUpdate.link_updateOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return LinkUpdate.internal_static_link_update_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return LinkUpdate.internal_static_link_update_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        LinkUpdate.link_update.class, LinkUpdate.link_update.Builder.class);
            }

            // Construct using LinkUpdate.link_update.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent
            ) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = 0L;

                creator_ = "";

                url_ = "";

                description_ = "";

                tgChatIds_ = emptyLongList();
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return LinkUpdate.internal_static_link_update_descriptor;
            }

            @java.lang.Override
            public LinkUpdate.link_update getDefaultInstanceForType() {
                return LinkUpdate.link_update.getDefaultInstance();
            }

            @java.lang.Override
            public LinkUpdate.link_update build() {
                LinkUpdate.link_update result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public LinkUpdate.link_update buildPartial() {
                LinkUpdate.link_update result = new LinkUpdate.link_update(this);
                int from_bitField0_ = bitField0_;
                result.id_ = id_;
                result.creator_ = creator_;
                result.url_ = url_;
                result.description_ = description_;
                if (((bitField0_ & 0x00000001) != 0)) {
                    tgChatIds_.makeImmutable();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.tgChatIds_ = tgChatIds_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value
            ) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field
            ) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof
            ) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value
            ) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value
            ) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof LinkUpdate.link_update) {
                    return mergeFrom((LinkUpdate.link_update) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(LinkUpdate.link_update other) {
                if (other == LinkUpdate.link_update.getDefaultInstance()) {
                    return this;
                }
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (!other.getCreator().isEmpty()) {
                    creator_ = other.creator_;
                    onChanged();
                }
                if (!other.getUrl().isEmpty()) {
                    url_ = other.url_;
                    onChanged();
                }
                if (!other.getDescription().isEmpty()) {
                    description_ = other.description_;
                    onChanged();
                }
                if (!other.tgChatIds_.isEmpty()) {
                    if (tgChatIds_.isEmpty()) {
                        tgChatIds_ = other.tgChatIds_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureTgChatIdsIsMutable();
                        tgChatIds_.addAll(other.tgChatIds_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry
            )
                throws java.io.IOException {
                LinkUpdate.link_update parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (LinkUpdate.link_update) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private long id_;

            /**
             * <code>int64 id = 1;</code>
             *
             * @return The id.
             */
            @java.lang.Override
            public long getId() {
                return id_;
            }

            /**
             * <code>int64 id = 1;</code>
             *
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 id = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object creator_ = "";

            /**
             * <code>string creator = 2;</code>
             *
             * @return The creator.
             */
            public java.lang.String getCreator() {
                java.lang.Object ref = creator_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    creator_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string creator = 2;</code>
             *
             * @return The bytes for creator.
             */
            public com.google.protobuf.ByteString
            getCreatorBytes() {
                java.lang.Object ref = creator_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    creator_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string creator = 2;</code>
             *
             * @param value The creator to set.
             * @return This builder for chaining.
             */
            public Builder setCreator(
                java.lang.String value
            ) {
                if (value == null) {
                    throw new NullPointerException();
                }

                creator_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string creator = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCreator() {

                creator_ = getDefaultInstance().getCreator();
                onChanged();
                return this;
            }

            /**
             * <code>string creator = 2;</code>
             *
             * @param value The bytes for creator to set.
             * @return This builder for chaining.
             */
            public Builder setCreatorBytes(
                com.google.protobuf.ByteString value
            ) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                creator_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object url_ = "";

            /**
             * <code>string url = 3;</code>
             *
             * @return The url.
             */
            public java.lang.String getUrl() {
                java.lang.Object ref = url_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    url_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string url = 3;</code>
             *
             * @return The bytes for url.
             */
            public com.google.protobuf.ByteString
            getUrlBytes() {
                java.lang.Object ref = url_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    url_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string url = 3;</code>
             *
             * @param value The url to set.
             * @return This builder for chaining.
             */
            public Builder setUrl(
                java.lang.String value
            ) {
                if (value == null) {
                    throw new NullPointerException();
                }

                url_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string url = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUrl() {

                url_ = getDefaultInstance().getUrl();
                onChanged();
                return this;
            }

            /**
             * <code>string url = 3;</code>
             *
             * @param value The bytes for url to set.
             * @return This builder for chaining.
             */
            public Builder setUrlBytes(
                com.google.protobuf.ByteString value
            ) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                url_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object description_ = "";

            /**
             * <code>string description = 4;</code>
             *
             * @return The description.
             */
            public java.lang.String getDescription() {
                java.lang.Object ref = description_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    description_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string description = 4;</code>
             *
             * @return The bytes for description.
             */
            public com.google.protobuf.ByteString
            getDescriptionBytes() {
                java.lang.Object ref = description_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    description_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string description = 4;</code>
             *
             * @param value The description to set.
             * @return This builder for chaining.
             */
            public Builder setDescription(
                java.lang.String value
            ) {
                if (value == null) {
                    throw new NullPointerException();
                }

                description_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string description = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearDescription() {

                description_ = getDefaultInstance().getDescription();
                onChanged();
                return this;
            }

            /**
             * <code>string description = 4;</code>
             *
             * @param value The bytes for description to set.
             * @return This builder for chaining.
             */
            public Builder setDescriptionBytes(
                com.google.protobuf.ByteString value
            ) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                description_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.Internal.LongList tgChatIds_ = emptyLongList();

            private void ensureTgChatIdsIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    tgChatIds_ = mutableCopy(tgChatIds_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated int64 tgChatIds = 5;</code>
             *
             * @return A list containing the tgChatIds.
             */
            public java.util.List<java.lang.Long>
            getTgChatIdsList() {
                return ((bitField0_ & 0x00000001) != 0) ?
                    java.util.Collections.unmodifiableList(tgChatIds_) : tgChatIds_;
            }

            /**
             * <code>repeated int64 tgChatIds = 5;</code>
             *
             * @return The count of tgChatIds.
             */
            public int getTgChatIdsCount() {
                return tgChatIds_.size();
            }

            /**
             * <code>repeated int64 tgChatIds = 5;</code>
             *
             * @param index The index of the element to return.
             * @return The tgChatIds at the given index.
             */
            public long getTgChatIds(int index) {
                return tgChatIds_.getLong(index);
            }

            /**
             * <code>repeated int64 tgChatIds = 5;</code>
             *
             * @param index The index to set the value at.
             * @param value The tgChatIds to set.
             * @return This builder for chaining.
             */
            public Builder setTgChatIds(
                int index, long value
            ) {
                ensureTgChatIdsIsMutable();
                tgChatIds_.setLong(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int64 tgChatIds = 5;</code>
             *
             * @param value The tgChatIds to add.
             * @return This builder for chaining.
             */
            public Builder addTgChatIds(long value) {
                ensureTgChatIdsIsMutable();
                tgChatIds_.addLong(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int64 tgChatIds = 5;</code>
             *
             * @param values The tgChatIds to add.
             * @return This builder for chaining.
             */
            public Builder addAllTgChatIds(
                java.lang.Iterable<? extends java.lang.Long> values
            ) {
                ensureTgChatIdsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, tgChatIds_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int64 tgChatIds = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTgChatIds() {
                tgChatIds_ = emptyLongList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields
            ) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields
            ) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:link_update)
        }

        // @@protoc_insertion_point(class_scope:link_update)
        private static final LinkUpdate.link_update DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new LinkUpdate.link_update();
        }

        public static LinkUpdate.link_update getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<link_update>
            PARSER = new com.google.protobuf.AbstractParser<link_update>() {
            @java.lang.Override
            public link_update parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry
            )
                throws com.google.protobuf.InvalidProtocolBufferException {
                return new link_update(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<link_update> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<link_update> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public LinkUpdate.link_update getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_link_update_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_link_update_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\021link_update.proto\"_\n\013link_update\022\n\n\002id" +
                "\030\001 \001(\003\022\017\n\007creator\030\002 \001(\t\022\013\n\003url\030\003 \001(\t\022\023\n\013" +
                "description\030\004 \001(\t\022\021\n\ttgChatIds\030\005 \003(\003b\006pr" +
                "oto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(
                descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {
                }
            );
        internal_static_link_update_descriptor =
            getDescriptor().getMessageTypes().get(0);
        internal_static_link_update_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_link_update_descriptor,
            new java.lang.String[] {"Id", "Creator", "Url", "Description", "TgChatIds",}
        );
    }

    // @@protoc_insertion_point(outer_class_scope)
}
