package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.Relation;
import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class RelationRecord extends UpdatableRecordImpl<RelationRecord>
    implements Record5<Long, Long, Long, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>RELATION.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>RELATION.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>RELATION.CHAT_ID</code>.
     */
    public void setChatId(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>RELATION.CHAT_ID</code>.
     */
    @Nullable
    public Long getChatId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>RELATION.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>RELATION.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>RELATION.CREATED_AT</code>.
     */
    public void setCreatedAt(@Nullable OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>RELATION.CREATED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>RELATION.CREATED_BY</code>.
     */
    public void setCreatedBy(@Nullable String value) {
        set(4, value);
    }

    /**
     * Getter for <code>RELATION.CREATED_BY</code>.
     */
    @Size(max = 1000000000)
    @Nullable
    public String getCreatedBy() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row5<Long, Long, Long, OffsetDateTime, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row5<Long, Long, Long, OffsetDateTime, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Relation.RELATION.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return Relation.RELATION.CHAT_ID;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return Relation.RELATION.LINK_ID;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field4() {
        return Relation.RELATION.CREATED_AT;
    }

    @Override
    @NotNull
    public Field<String> field5() {
        return Relation.RELATION.CREATED_BY;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getChatId();
    }

    @Override
    @Nullable
    public Long component3() {
        return getLinkId();
    }

    @Override
    @Nullable
    public OffsetDateTime component4() {
        return getCreatedAt();
    }

    @Override
    @Nullable
    public String component5() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getChatId();
    }

    @Override
    @Nullable
    public Long value3() {
        return getLinkId();
    }

    @Override
    @Nullable
    public OffsetDateTime value4() {
        return getCreatedAt();
    }

    @Override
    @Nullable
    public String value5() {
        return getCreatedBy();
    }

    @Override
    @NotNull
    public RelationRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public RelationRecord value2(@Nullable Long value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public RelationRecord value3(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public RelationRecord value4(@Nullable OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public RelationRecord value5(@Nullable String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    @NotNull
    public RelationRecord values(
        @Nullable Long value1,
        @Nullable Long value2,
        @Nullable Long value3,
        @Nullable OffsetDateTime value4,
        @Nullable String value5
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelationRecord
     */
    public RelationRecord() {
        super(Relation.RELATION);
    }

    /**
     * Create a detached, initialised RelationRecord
     */
    @ConstructorProperties({"id", "chatId", "linkId", "createdAt", "createdBy"})
    public RelationRecord(
        @Nullable Long id,
        @Nullable Long chatId,
        @Nullable Long linkId,
        @Nullable OffsetDateTime createdAt,
        @Nullable String createdBy
    ) {
        super(Relation.RELATION);

        setId(id);
        setChatId(chatId);
        setLinkId(linkId);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RelationRecord
     */
    public RelationRecord(edu.java.domain.jooq.tables.pojos.Relation value) {
        super(Relation.RELATION);

        if (value != null) {
            setId(value.getId());
            setChatId(value.getChatId());
            setLinkId(value.getLinkId());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            resetChangedOnNotNull();
        }
    }
}
