package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.Tgchat;
import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TgchatRecord extends UpdatableRecordImpl<TgchatRecord> implements Record3<Long, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TGCHAT.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>TGCHAT.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>TGCHAT.CREATED_AT</code>.
     */
    public void setCreatedAt(@Nullable OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>TGCHAT.CREATED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>TGCHAT.CREATED_BY</code>.
     */
    public void setCreatedBy(@Nullable String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TGCHAT.CREATED_BY</code>.
     */
    @Size(max = 1000000000)
    @Nullable
    public String getCreatedBy() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, OffsetDateTime, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, OffsetDateTime, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Tgchat.TGCHAT.CHAT_ID;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field2() {
        return Tgchat.TGCHAT.CREATED_AT;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return Tgchat.TGCHAT.CREATED_BY;
    }

    @Override
    @NotNull
    public Long component1() {
        return getChatId();
    }

    @Override
    @Nullable
    public OffsetDateTime component2() {
        return getCreatedAt();
    }

    @Override
    @Nullable
    public String component3() {
        return getCreatedBy();
    }

    @Override
    @NotNull
    public Long value1() {
        return getChatId();
    }

    @Override
    @Nullable
    public OffsetDateTime value2() {
        return getCreatedAt();
    }

    @Override
    @Nullable
    public String value3() {
        return getCreatedBy();
    }

    @Override
    @NotNull
    public TgchatRecord value1(@NotNull Long value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public TgchatRecord value2(@Nullable OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public TgchatRecord value3(@Nullable String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    @NotNull
    public TgchatRecord values(@NotNull Long value1, @Nullable OffsetDateTime value2, @Nullable String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TgchatRecord
     */
    public TgchatRecord() {
        super(Tgchat.TGCHAT);
    }

    /**
     * Create a detached, initialised TgchatRecord
     */
    @ConstructorProperties({ "chatId", "createdAt", "createdBy" })
    public TgchatRecord(@NotNull Long chatId, @Nullable OffsetDateTime createdAt, @Nullable String createdBy) {
        super(Tgchat.TGCHAT);

        setChatId(chatId);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TgchatRecord
     */
    public TgchatRecord(edu.java.domain.jooq.tables.pojos.Tgchat value) {
        super(Tgchat.TGCHAT);

        if (value != null) {
            setChatId(value.getChatId());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            resetChangedOnNotNull();
        }
    }
}
