app:
  scheduler:
    enable: true
    interval: 5s
    force-check-delay: 10s

  client-base-url:
    github-uri: https://api.github.com
    stackoverflow-uri: https://api.stackexchange.com/2.3
    bot-url: http://localhost:8090


spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
