app:
  scheduler:
    enable: true
    interval: 5s
    force-check-delay: 10s

  client-base-url:
    github-url: https://api.github.com/repos/
    stackoverflow-url: https://api.stackexchange.com/2.3/questions/
    bot-url: http://localhost:8090

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
