app:
  scheduler:
    enable: true
    interval: 5s
    force-check-delay: 10s

  database-access-type: jooq # JPA, JOOQ

  client-base-url:
    github-uri: https://api.github.com
    stackoverflow-uri: https://api.stackexchange.com/2.3
    bot-url: http://localhost:8090


spring:
  application:
    name: scrapper
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
