app:
  telegram-token: ${bot_token}
  scrapper-base-uri: http://localhost:8080
  retry:
    back-off-policy: exponential
    httpStatuses: INTERNAL_SERVER_ERROR, UNAUTHORIZED
    max-attempts: 3
    delay: 1s

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
