package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.TgchatRecord;
import java.time.OffsetDateTime;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tgchat extends TableImpl<TgchatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TGCHAT</code>
     */
    public static final Tgchat TGCHAT = new Tgchat();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<TgchatRecord> getRecordType() {
        return TgchatRecord.class;
    }

    /**
     * The column <code>TGCHAT.CHAT_ID</code>.
     */
    public final TableField<TgchatRecord, Long> CHAT_ID = createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>TGCHAT.CREATED_AT</code>.
     */
    public final TableField<TgchatRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("LOCALTIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>TGCHAT.CREATED_BY</code>.
     */
    public final TableField<TgchatRecord, String> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(1000000000).nullable(false).defaultValue(DSL.field(DSL.raw("'themlord'"), SQLDataType.VARCHAR)), this, "");

    private Tgchat(Name alias, Table<TgchatRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tgchat(Name alias, Table<TgchatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>TGCHAT</code> table reference
     */
    public Tgchat(String alias) {
        this(DSL.name(alias), TGCHAT);
    }

    /**
     * Create an aliased <code>TGCHAT</code> table reference
     */
    public Tgchat(Name alias) {
        this(alias, TGCHAT);
    }

    /**
     * Create a <code>TGCHAT</code> table reference
     */
    public Tgchat() {
        this(DSL.name("TGCHAT"), null);
    }

    public <O extends Record> Tgchat(Table<O> child, ForeignKey<O, TgchatRecord> key) {
        super(child, key, TGCHAT);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<TgchatRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    @Override
    @NotNull
    public Tgchat as(String alias) {
        return new Tgchat(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Tgchat as(Name alias) {
        return new Tgchat(alias, this);
    }

    @Override
    @NotNull
    public Tgchat as(Table<?> alias) {
        return new Tgchat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Tgchat rename(String name) {
        return new Tgchat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Tgchat rename(Name name) {
        return new Tgchat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Tgchat rename(Table<?> name) {
        return new Tgchat(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, OffsetDateTime, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super OffsetDateTime, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super OffsetDateTime, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
