package edu.java.domain.jooq.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
@Data
@NoArgsConstructor
public class Links implements Serializable {
    private static final long serialVersionUID = 1L;
    private Long id;
    private String linkUri;
    private OffsetDateTime createdAt;
    private String createdBy;
    private String content;
    private OffsetDateTime lastModifying;

    public Links(Links value) {
        this.id = value.id;
        this.linkUri = value.linkUri;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
        this.content = value.content;
        this.lastModifying = value.lastModifying;
    }

    @ConstructorProperties({"id", "linkUri", "createdAt", "createdBy", "content", "lastModifying"})
    public Links(
        @Nullable Long id,
        @NotNull String linkUri,
        @NotNull OffsetDateTime createdAt,
        @Nullable String createdBy,
        @Nullable String content,
        @Nullable OffsetDateTime lastModifying
    ) {
        this.id = id;
        this.linkUri = linkUri;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.content = content;
        this.lastModifying = lastModifying;
    }
}
