package edu.java.domain.jooq.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
@NoArgsConstructor
@Data
public class Subscriptions implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long chatId;
    private Long linkId;
    private OffsetDateTime createdAt;
    private String createdBy;

    public Subscriptions(Subscriptions value) {
        this.chatId = value.chatId;
        this.linkId = value.linkId;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
    }

    @ConstructorProperties({"chatId", "linkId", "createdAt", "createdBy"})
    public Subscriptions(
        @NotNull Long chatId,
        @NotNull Long linkId,
        @NotNull OffsetDateTime createdAt,
        @Nullable String createdBy
    ) {
        this.chatId = chatId;
        this.linkId = linkId;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }
}
