package edu.java.domain.jooq;

import edu.java.domain.jooq.tables.Link;
import edu.java.domain.jooq.tables.Relation;
import edu.java.domain.jooq.tables.Tgchat;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>RELATION</code>.
     */
    public static final Relation RELATION = Relation.RELATION;

    /**
     * The table <code>TGCHAT</code>.
     */
    public static final Tgchat TGCHAT = Tgchat.TGCHAT;
}
